### ISSUE TITLE
Unable to connect clients & Unable to perform backups

### ISSUE THREAD

**Issue by Justahobby01** [Macro-Deck-App/Macro-Deck#325] opened 2022-12-01 16:54 UTC
I'm not sure what happened, but Macro-Deck worked flawlessly for 6+ months before this.

**Log file**
1. **Unable to connect clients**
`Connection request from (device)`
`(device) connection closed`
`[Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.LoadDevices() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 61
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.DeviceManagerPage_Load(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 34
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at SuchByte.MacroDeck.GUI.MainWindow.SetView(Control view) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 96
   at SuchByte.MacroDeck.GUI.MainWindow.BtnDeviceManager_Click(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 237
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

2. **Unable to perform backups**
`[Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.LoadDevices() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 61
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.DeviceManagerPage_Load(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 34
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at SuchByte.MacroDeck.GUI.MainWindow.SetView(Control view) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 96
   at SuchByte.MacroDeck.GUI.MainWindow.BtnDeviceManager_Click(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 237
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by jbcarreon123** [comment] 2022-12-02 13:08
## Please delete `%temp%\Macro Deck\devices.json` and restart Macro Deck.

**Comment by SuchByte** [comment] 2023-01-07 19:33
>Please delete %temp%\Macro Deck\devices.json and restart Macro Deck.

@Justahobby01 Did this work for you?

**Comment by BacchusZA** [comment] 2023-05-07 18:31
I'm having the same issue (I've not tried restoring backups though), and cannot find the devices.json to delete it. I find MacroDeck extremely useful, so any help resolving this would be greatly appreciated.


04:07:10 [Macro Deck] [Info] >> 
==========================================
04:07:10 [Macro Deck] [Info] >> Starting Macro Deck version 2.12.0 build 221941808
04:07:10 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
04:07:10 [Macro Deck] [Info] >> OS: Windows 8 build 9200 64 bit
04:07:10 [Macro Deck] [Info] >> Network interfaces: 
ProtonVPN TUN - 169.254.160.23
Ethernet - 192.168.1.55
Local Area Connection - 169.254.196.106
WiFi - 169.254.198.40
Local Area Connection* 9 - 169.254.24.162
Local Area Connection* 10 - 169.254.120.18
Bluetooth Network Connection - 169.254.103.3
Loopback Pseudo-Interface 1 - 127.0.0.1
04:07:10 [Macro Deck] [Info] >> Loading language files...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
04:07:10 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
04:07:10 [Macro Deck] [Info] >> Successfully read configuration file
04:07:10 [Macro Deck] [Info] >> Set language to English
04:07:10 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
04:07:11 [Macro Deck] [Info] >> VariableManager: 96 variables found
04:07:11 [Macro Deck] [Info] >> PluginManager: Loading plugins...
04:07:11 [Macro Deck] [Info] >> Loading plugin Soundboard4MacroDeck
04:07:11 [Macro Deck] [Info] >> Loading plugin Macro Deck Media Controls
04:07:11 [Macro Deck] [Info] >> Loading plugin OBS-WebSocket Plugin
04:07:12 [Macro Deck] [Info] >> Loading plugin Windows Utils
04:07:12 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
04:07:12 [Macro Deck] [Info] >> Soundboard4MacroDeck version 1.0.0 enabled (took 30ms)
04:07:12 [Macro Deck] [Info] >> Macro Deck Media Controls version 1.1.1 enabled (took 0ms)
04:07:12 [Macro Deck] [Info] >> OBS-WebSocket Plugin version 1.4.2 enabled (took 112ms)
04:07:12 [Macro Deck] [Info] >> Windows Utils version 1.4.1 enabled (took 14ms)
04:07:12 [Macro Deck] [Info] >> This action button version 2.12.0.221941808 enabled (took 1ms)
04:07:12 [Macro Deck] [Info] >> Macro Deck variables version 2.12.0.221941808 enabled (took 1ms)
04:07:12 [Macro Deck] [Info] >> Macro Deck folder version 2.12.0.221941808 enabled (took 0ms)
04:07:12 [Macro Deck] [Info] >> Device version 2.12.0.221941808 enabled (took 1ms)
04:07:12 [Macro Deck] [Info] >> PluginManager: Plugins enabled
04:07:12 [Macro Deck] [Info] >> IconManager: Loading icon packs...
04:07:12 [Macro Deck] [Info] >> IconManager: Loaded 13 icon packs
04:07:12 [Macro Deck] [Info] >> ProfileManager: Loading profiles...
04:07:12 [Macro Deck] [Info] >> Loaded 1 profiles
04:07:12 [Macro Deck] [Info] >> Starting websocket server @ 192.168.1.55:8191
04:07:13 [Macro Deck] [Info] >> Starting USB websocket server @ 127.0.0.1:8191
04:07:13 [Macro Deck] [Warning] >> ADBServerHelper: Cannot start adb server at C:\Users\bacch\AppData\Local\Temp\.net\Macro Deck 2\SXBJAH20YW6MeYtPR3JnNFjfmGmxWL0=\Android Debug Bridge\adb.exe: File not found
04:07:13 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
04:07:13 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server complete
04:07:13 [Macro Deck] [Info] >> Macro Deck startup finished (took 3172ms)
15:43:30 [Macro Deck] [Info] >> 
==========================================
15:43:30 [Macro Deck] [Info] >> Starting Macro Deck version 2.12.0 build 221941808
15:43:30 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
15:43:30 [Macro Deck] [Info] >> OS: Windows 8 build 9200 64 bit
15:43:31 [Macro Deck] [Info] >> Network interfaces: 
ProtonVPN TUN - 169.254.160.23
Ethernet - 192.168.1.55
Local Area Connection - 169.254.196.106
WiFi - 169.254.198.40
Local Area Connection* 9 - 169.254.24.162
Local Area Connection* 10 - 169.254.120.18
Bluetooth Network Connection - 169.254.103.3
Loopback Pseudo-Interface 1 - 127.0.0.1
15:43:31 [Macro Deck] [Info] >> Loading language files...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
15:43:31 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
15:43:31 [Macro Deck] [Info] >> Successfully read configuration file
15:43:31 [Macro Deck] [Info] >> Set language to English
15:43:31 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
15:43:31 [Macro Deck] [Info] >> VariableManager: 96 variables found
15:43:31 [Macro Deck] [Info] >> PluginManager: Loading plugins...
15:43:32 [Macro Deck] [Info] >> Loading plugin Soundboard4MacroDeck
15:43:32 [Macro Deck] [Info] >> Loading plugin Macro Deck Media Controls
15:43:32 [Macro Deck] [Info] >> Loading plugin OBS-WebSocket Plugin
15:43:33 [Macro Deck] [Info] >> Loading plugin Windows Utils
15:43:33 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
15:43:33 [Macro Deck] [Info] >> Soundboard4MacroDeck version 1.0.0 enabled (took 37ms)
15:43:33 [Macro Deck] [Info] >> Macro Deck Media Controls version 1.1.1 enabled (took 0ms)
15:43:33 [Macro Deck] [Info] >> OBS-WebSocket Plugin version 1.4.2 enabled (took 256ms)
15:43:33 [Macro Deck] [Info] >> Windows Utils version 1.4.1 enabled (took 28ms)
15:43:33 [Macro Deck] [Info] >> This action button version 2.12.0.221941808 enabled (took 0ms)
15:43:33 [Macro Deck] [Info] >> Macro Deck variables version 2.12.0.221941808 enabled (took 1ms)
15:43:33 [Macro Deck] [Info] >> Macro Deck folder version 2.12.0.221941808 enabled (took 0ms)
15:43:33 [Macro Deck] [Info] >> Device version 2.12.0.221941808 enabled (took 0ms)
15:43:33 [Macro Deck] [Info] >> PluginManager: Plugins enabled
15:43:33 [Macro Deck] [Info] >> IconManager: Loading icon packs...
15:43:34 [Macro Deck] [Info] >> IconManager: Loaded 13 icon packs
15:43:34 [Macro Deck] [Info] >> ProfileManager: Loading profiles...
15:43:34 [Macro Deck] [Info] >> Loaded 1 profiles
15:43:34 [Macro Deck] [Info] >> Starting websocket server @ 192.168.1.55:8191
15:43:35 [Macro Deck] [Info] >> Starting USB websocket server @ 127.0.0.1:8191
15:43:35 [Macro Deck] [Warning] >> ADBServerHelper: Cannot start adb server at C:\Users\bacch\AppData\Local\Temp\.net\Macro Deck 2\SXBJAH20YW6MeYtPR3JnNFjfmGmxWL0=\Android Debug Bridge\adb.exe: File not found
15:43:35 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
15:43:35 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server complete
15:43:35 [Macro Deck] [Info] >> Macro Deck startup finished (took 4602ms)
20:12:19 [Macro Deck] [Info] >> 
==========================================
20:12:19 [Macro Deck] [Info] >> Starting Macro Deck version 2.12.0 build 221941808
20:12:19 [Macro Deck] [Info] >> Executable: C:\Program Files\Macro Deck\Macro Deck 2.exe
20:12:19 [Macro Deck] [Info] >> OS: Windows 8 build 9200 64 bit
20:12:19 [Macro Deck] [Info] >> Network interfaces: 
ProtonVPN TUN - 169.254.160.23
Ethernet - 192.168.1.55
Local Area Connection - 169.254.196.106
WiFi - 169.254.198.40
Local Area Connection* 9 - 169.254.24.162
Bluetooth Network Connection - 169.254.103.3
Loopback Pseudo-Interface 1 - 127.0.0.1
20:12:19 [Macro Deck] [Info] >> Loading language files...
20:12:19 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
20:12:20 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
20:12:20 [Macro Deck] [Info] >> Successfully read configuration file
20:12:20 [Macro Deck] [Info] >> Set language to English
20:12:20 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
20:12:20 [Macro Deck] [Info] >> VariableManager: 96 variables found
20:12:20 [Macro Deck] [Info] >> PluginManager: Loading plugins...
20:12:20 [Macro Deck] [Info] >> Loading plugin Soundboard4MacroDeck
20:12:20 [Macro Deck] [Info] >> Loading plugin Macro Deck Media Controls
20:12:20 [Macro Deck] [Info] >> Loading plugin OBS-WebSocket Plugin
20:12:20 [Macro Deck] [Info] >> Loading plugin Windows Utils
20:12:21 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
20:12:21 [Macro Deck] [Info] >> Soundboard4MacroDeck version 1.0.0 enabled (took 26ms)
20:12:21 [Macro Deck] [Info] >> Macro Deck Media Controls version 1.1.1 enabled (took 1ms)
20:12:21 [Macro Deck] [Info] >> OBS-WebSocket Plugin version 1.4.2 enabled (took 88ms)
20:12:21 [Macro Deck] [Info] >> Windows Utils version 1.4.1 enabled (took 11ms)
20:12:21 [Macro Deck] [Info] >> This action button version 2.12.0.221941808 enabled (took 1ms)
20:12:21 [Macro Deck] [Info] >> Macro Deck variables version 2.12.0.221941808 enabled (took 1ms)
20:12:21 [Macro Deck] [Info] >> Macro Deck folder version 2.12.0.221941808 enabled (took 0ms)
20:12:21 [Macro Deck] [Info] >> Device version 2.12.0.221941808 enabled (took 0ms)
20:12:21 [Macro Deck] [Info] >> PluginManager: Plugins enabled
20:12:21 [Macro Deck] [Info] >> IconManager: Loading icon packs...
20:12:21 [Macro Deck] [Info] >> IconManager: Loaded 13 icon packs
20:12:21 [Macro Deck] [Info] >> ProfileManager: Loading profiles...
20:12:21 [Macro Deck] [Info] >> Loaded 1 profiles
20:12:21 [Macro Deck] [Info] >> Starting websocket server @ 192.168.1.55:8191
20:12:21 [Macro Deck] [Info] >> Starting USB websocket server @ 127.0.0.1:8191
20:12:21 [Macro Deck] [Warning] >> ADBServerHelper: Cannot start adb server at C:\Users\bacch\AppData\Local\Temp\.net\Macro Deck 2\SXBJAH20YW6MeYtPR3JnNFjfmGmxWL0=\Android Debug Bridge\adb.exe: File not found
20:12:21 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
20:12:21 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server complete
20:12:21 [Macro Deck] [Info] >> Macro Deck startup finished (took 2085ms)
20:12:44 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.LoadDevices() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 61
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.DeviceManagerPage_Load(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 34
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at SuchByte.MacroDeck.GUI.MainWindow.SetView(Control view) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 96
   at SuchByte.MacroDeck.GUI.MainWindow.BtnDeviceManager_Click(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 237
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
20:12:59 [Macro Deck] [Info] >> Connection request from A4HZPT6CC
20:12:59 [Macro Deck] [Info] >> A4HZPT6CC connection closed
20:12:59 [Macro Deck] [Info] >> A4HZPT6CC connection closed
20:13:03 [Macro Deck] [Info] >> Connection request from A4HZPT6CC
20:13:03 [Macro Deck] [Info] >> A4HZPT6CC connection closed
20:13:03 [Macro Deck] [Info] >> A4HZPT6CC connection closed
20:13:10 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.LoadDevices() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 61
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeviceManagerView.DeviceManagerPage_Load(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\DeviceManagerView.cs:line 34
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at SuchByte.MacroDeck.GUI.MainWindow.SetView(Control view) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 96
   at SuchByte.MacroDeck.GUI.MainWindow.BtnDeviceManager_Click(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindow.cs:line 237
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by manuelmayer-dev** [comment] 2023-06-24 20:13
Deleting the devices.json in %Appdata%\Macro deck should fix this for now. The connection issue is caused by a wrong configured system. https://github.com/Macro-Deck-App/Macro-Deck/wiki/Frequently-asked-questions

**Closed by manuelmayer-dev** 2023-06-24 20:13 UTC
Labels: bug
